export { default as ArrowDown } from './ArrowDown'
export { default as Bag } from './Bag'
export { default as CarIcon } from './CarIcon'
export { default as DeleteIcon } from './DeleteIcon'
export { default as Heart } from './Heart'
export { default as HomeIcon } from './Home'
export { default as InstaLogo } from './Insta'
export { default as Map } from './Map'
export { default as Percent } from './Percent'
export { default as Phone } from './Phone'
export { default as ProductBag } from './ProductBag'
export { default as Scales } from './Scales'
export { default as Search } from './Search'
export { default as SecurityIcon } from './SecurityIcon'
export { default as TGLogo } from './TG-logo'
export { default as TwitterLogo } from './Twitter'
export { default as User } from './User'

